npm install -g grunt
npm install -g grunt-cli
npm install -g express
npm install -g express-generator
npm install -g gulp
npm install -g node-sass
npm install -g requirejs
npm install -g sails
npm install -g pm2
npm install -g node-inspector
npm install -g nodemon
npm install -g jshint
npm install -g csslint
npm install -g bower
npm install -g yo